language: php

addons:
  postgresql: "9.6"

services:
  - mysql
  - postgresql
  - docker
  - redis-server # Add Redis Server to the build.

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 7.2
 - 7.3
 - 7.4

env:
 global:
  - MOODLE_BRANCH=MOODLE_310_STABLE
 matrix:
  - DB=pgsql
# - DB=mysqli - MySQL is disabled because this plugin does not need a database at all.

before_install:
  - phpenv config-rm xdebug.ini
  - printf "\n" | pecl install -f redis # Install Redis PHP Extension without prompting for anything. And do it forcibly as the Redis extension might already be installed.
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpdoc
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat --dump
